app:
  replicas: 1
  name: hello
image: {}
service:
  port: 80
  internalPort: 80
  scheme: http
healthcheck:
  enabled: false
hpa:
  enabled: false
container:
  command: ""
image:
  repositoryBase: 069987675187.dkr.ecr.eu-central-1.amazonaws.com
domain: "meetup-peaks.ddns.net"
clusterIssuerName: letsencrypt
